name: "Jest error notification to Slack"
description: "Send jest error notification to slack"
inputs:
  token:
    description: "Slack bot token"
    required: true
  channel:
    description: "Channel id/name to post"
    required: true
  path:
    description: "jest result json path"
    required: true
  message:
    description: "Slack message"

runs:
  using: "node12"
  main: "dist/index.js"
